### PR TITLE
JSON-driven HTML version for the modern web

### PR DESCRIPTION
**Pull request by rbirkby**
Implements an HTML version of the dark poster, dynamically generated.

1. JSON-driven
1. Built on the modern web platform
1. Intended to be published by GitHub Pages (on Master/docs)

eg: https://rbirkby.github.io/google-cloud-4-words/

## Rationale

Some people/companies may want to overlay their own data on top of this poster - for example providing a view of the products available on a region-by-region basis. Having the data source as JSON with a template-driven rendering allows this poster to be customized further.

### CODE REVIEW

**Comment by gregsramblings** [comment]
This is super awesome! I want to move to this model.. way easier to maintain. Have you given any thought to making it responsive...so if viewed on a mobile device, it's one column, etc..

Also, I need the docs link to somehow be integrated because we don't do a consistent job on our end making sure that the docs link is available from the product landing page (although we're working on fixing this). Any thoughts on that?

I *really* appreciate the work on this!

**Comment by Jeffrey-D-Pierce** [comment]
Perhaps making the links go to Google search, instead of trying to maintain the product landing page list. To help narrow the search, always include "google cloud" with the title. For example:
```
const product = "Data Catalog"  
const href=`https://www.google.com/search?as_q=google%20cloud%20${product.replace(/ /g, '%20')}&s_qdr=y`
<a id="name" href="${href}" >${product}</a>
```
This will reduce the maintenance, probably provide the landing page, and will give more information than just what the landing page offers.

**Comment by rbirkby** [comment]
If GCPs product pages are illogical and non-uniform, this is an opportunity to fix that rather than workaround the problem.

**Comment by vredchenko** [comment]
Better still - we aught to package the cheatsheat as an ObservableHQ notebook which can auto-update itself, email maintainers when it needs help, tweet news and present cheatsheet data as both JSON and visual representation (and serve this data via API).

**Pull request closed without merging**
